language: go

before_install:
    #- env GO111MODULE=on go build
     - go get github.com/fatih/color
     - go get github.com/sensorario/gol
     - go get github.com/stretchr/testify/assert

go:
    - 1.12.1
